#
# BenjiLeGnard minimal zsh config
#

# oh-my-zsh path
export ZSH="$HOME/.oh-my-zsh"
# no theme, starship is our prompt
export ZSH_THEME=""
# optimize nvm loading
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('nvim')
export NVM_LAZY_LOAD=true
# zsh plugins
plugins=(git ng nvm npm tmux gh)

source $ZSH/oh-my-zsh.sh

# starship.rs prompt
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# set neovim as editor and pager
export EDITOR="nvim"
export MANPAGER="nvim +Man!"

# vi mode
set -o vi
bindkey -M viins 'jj' vi-cmd-mode

# load aliases and functions from config dir
for f in ~/.config/zsh/**/*.zsh; do
    source "$f"
done
