#
# BenjiLeGnard minimal zsh config
#

# to have cargo/rustup/rustc in path
source "$HOME/.cargo/env"
# oh-my-zsh path
export ZSH="$HOME/.oh-my-zsh"
# no theme, starship is our prompt
export ZSH_THEME=""
# zsh plugins
plugins=(git nvm)

source $ZSH/oh-my-zsh.sh

# starship.rs prompt
eval "$(starship init zsh)"

# set neovim as editor and pager
export EDITOR="nvim"
export MANPAGER="nvim +Man!"

